"""
Generate BH Insights Report with Visualizations
"""
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# Set style for dark theme
plt.style.use('dark_background')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

# Create output directory
os.makedirs('reports/figures', exist_ok=True)

# =============================================================================
# Load and prepare data
# =============================================================================
print("Loading BH Insights backtest data...")

# Read the full backtest results
bh_df = pd.read_csv('results/bh_insights_full_backtest.csv')

# Calculate alpha
bh_df['Alpha'] = bh_df['Strategy_Return_Pct'] - bh_df['BuyHold_Return_Pct']

# Sort by alpha for charts
bh_sorted = bh_df.sort_values('Alpha', ascending=False)

print(f"  Loaded {len(bh_df)} assets")

# =============================================================================
# Chart 1: Alpha by Asset (Horizontal Bar)
# =============================================================================
print("Generating alpha bar chart...")

fig, ax = plt.subplots(figsize=(14, 10))

# Color by positive/negative alpha
colors = ['#4ecdc4' if a >= 0 else '#ff6b6b' for a in bh_sorted['Alpha']]

bars = ax.barh(bh_sorted['Asset'], bh_sorted['Alpha'], color=colors,
               edgecolor='white', linewidth=0.5, alpha=0.85)

# Add zero line
ax.axvline(x=0, color='white', linewidth=1.5, linestyle='-', alpha=0.8)

# Add value labels
for bar, val in zip(bars, bh_sorted['Alpha']):
    x_pos = val + 2 if val >= 0 else val - 2
    ha = 'left' if val >= 0 else 'right'
    color = '#4ecdc4' if val >= 0 else '#ff6b6b'
    ax.text(x_pos, bar.get_y() + bar.get_height()/2, f'{val:+.1f}%',
            va='center', ha=ha, fontsize=9, fontweight='bold', color=color)

ax.set_xlabel('Alpha vs Buy & Hold (%)', fontsize=12)
ax.set_title('BH Insights Strategy: Alpha Generated by Asset\n(Strategy Return - Buy & Hold Return)',
             fontsize=14, fontweight='bold', pad=20)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Add summary annotation
positive_alpha = (bh_sorted['Alpha'] >= 0).sum()
total = len(bh_sorted)
ax.text(0.98, 0.02, f'{positive_alpha}/{total} assets beat buy & hold ({100*positive_alpha/total:.0f}%)',
        transform=ax.transAxes, ha='right', va='bottom', fontsize=11,
        bbox=dict(boxstyle='round', facecolor='#2d3436', alpha=0.8))

plt.tight_layout()
plt.savefig('reports/figures/bh_alpha_by_asset.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_alpha_by_asset.png")

# =============================================================================
# Chart 2: Strategy vs Buy & Hold Comparison
# =============================================================================
print("Generating strategy vs buy & hold comparison...")

# Only show assets with trades
traded_assets = bh_df[bh_df['Total_Trades'] > 0].sort_values('Alpha', ascending=True)

fig, ax = plt.subplots(figsize=(14, 8))

x = np.arange(len(traded_assets))
width = 0.35

bars1 = ax.bar(x - width/2, traded_assets['Strategy_Return_Pct'], width,
               label='Strategy Return', color='#4ecdc4', edgecolor='white', linewidth=0.5)
bars2 = ax.bar(x + width/2, traded_assets['BuyHold_Return_Pct'], width,
               label='Buy & Hold', color='#ff6b6b', edgecolor='white', linewidth=0.5, alpha=0.7)

ax.axhline(y=0, color='white', linewidth=1, linestyle='--', alpha=0.5)
ax.set_ylabel('Return (%)', fontsize=12)
ax.set_xlabel('Asset', fontsize=12)
ax.set_title('BH Insights: Strategy Return vs Buy & Hold (Assets with Trades Only)',
             fontsize=14, fontweight='bold', pad=20)
ax.set_xticks(x)
ax.set_xticklabels(traded_assets['Asset'], rotation=45, ha='right')
ax.legend(loc='upper left')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('reports/figures/bh_strategy_vs_buyhold.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_strategy_vs_buyhold.png")

# =============================================================================
# Chart 3: Win Rate vs Return Scatter
# =============================================================================
print("Generating win rate scatter plot...")

# Filter to assets with trades
scatter_df = bh_df[bh_df['Total_Trades'] > 0].copy()

fig, ax = plt.subplots(figsize=(12, 8))

# Bubble size based on trade count
sizes = scatter_df['Total_Trades'] * 30 + 100

# Color by alpha
colors = ['#4ecdc4' if a >= 0 else '#ff6b6b' for a in scatter_df['Alpha']]

scatter = ax.scatter(scatter_df['Win_Rate_Pct'], scatter_df['Strategy_Return_Pct'],
                     s=sizes, c=colors, alpha=0.7, edgecolors='white', linewidth=1)

# Add labels for key assets
for _, row in scatter_df.iterrows():
    if abs(row['Strategy_Return_Pct']) > 50 or row['Total_Trades'] > 10:
        ax.annotate(row['Asset'], (row['Win_Rate_Pct'], row['Strategy_Return_Pct']),
                   xytext=(5, 5), textcoords='offset points', fontsize=9, alpha=0.9)

# Add quadrant lines
ax.axhline(y=0, color='white', linewidth=1, linestyle='--', alpha=0.3)
ax.axvline(x=50, color='white', linewidth=1, linestyle='--', alpha=0.3)

# Quadrant labels
ax.text(80, 200, 'IDEAL\nHigh Win Rate\nPositive Return', ha='center', va='center',
        fontsize=10, alpha=0.4, color='#4ecdc4')
ax.text(20, -60, 'WORST\nLow Win Rate\nNegative Return', ha='center', va='center',
        fontsize=10, alpha=0.4, color='#ff6b6b')

ax.set_xlabel('Win Rate (%)', fontsize=12)
ax.set_ylabel('Strategy Return (%)', fontsize=12)
ax.set_title('Win Rate vs Strategy Return\n(Bubble size = trade count, Green = positive alpha)',
             fontsize=14, fontweight='bold', pad=20)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('reports/figures/bh_winrate_scatter.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_winrate_scatter.png")

# =============================================================================
# Chart 4: Trade Count Distribution
# =============================================================================
print("Generating trade count distribution...")

fig, ax = plt.subplots(figsize=(12, 6))

# Sort by trade count
trade_sorted = bh_df.sort_values('Total_Trades', ascending=True)

# Color by alpha
colors = ['#4ecdc4' if a >= 0 else '#ff6b6b' for a in trade_sorted['Alpha']]

bars = ax.barh(trade_sorted['Asset'], trade_sorted['Total_Trades'], color=colors,
               edgecolor='white', linewidth=0.5, alpha=0.85)

ax.set_xlabel('Number of Trades', fontsize=12)
ax.set_title('Trade Count by Asset\n(Green = positive alpha, Red = negative alpha)',
             fontsize=14, fontweight='bold', pad=20)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('reports/figures/bh_trade_distribution.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_trade_distribution.png")

# =============================================================================
# Chart 5: Portfolio Simulation
# =============================================================================
print("Generating portfolio simulation chart...")

# Calculate aggregate portfolio returns
starting_capital = 10000 * len(bh_df)
# Calculate final values from returns
bh_df['Final_Value'] = 10000 * (1 + bh_df['Strategy_Return_Pct']/100)
total_strategy_value = bh_df['Final_Value'].sum()
total_buyhold_value = 10000 * len(bh_df) * (1 + bh_df['BuyHold_Return_Pct'].mean()/100)

fig, ax = plt.subplots(figsize=(10, 6))

categories = ['Starting\nCapital', 'Strategy\nEnding Value', 'Buy & Hold\nEnding Value']
values = [starting_capital, total_strategy_value, total_buyhold_value]
colors = ['#636e72', '#4ecdc4', '#ff6b6b']

bars = ax.bar(categories, values, color=colors, edgecolor='white', linewidth=1)

# Add value labels
for bar, val in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5000, f'${val:,.0f}',
            ha='center', va='bottom', fontsize=12, fontweight='bold')

# Add percentage labels
strategy_pct = (total_strategy_value - starting_capital) / starting_capital * 100
buyhold_pct = (total_buyhold_value - starting_capital) / starting_capital * 100

ax.text(1, values[1] * 0.5, f'{strategy_pct:+.1f}%', ha='center', va='center',
        fontsize=14, fontweight='bold', color='white')
ax.text(2, values[2] * 0.5, f'{buyhold_pct:+.1f}%', ha='center', va='center',
        fontsize=14, fontweight='bold', color='white')

ax.set_ylabel('Portfolio Value ($)', fontsize=12)
ax.set_title(f'Portfolio Simulation: $10,000 × {len(bh_df)} Assets\n(Alpha: ${total_strategy_value - total_buyhold_value:,.0f})',
             fontsize=14, fontweight='bold', pad=20)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Format y-axis
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))

plt.tight_layout()
plt.savefig('reports/figures/bh_portfolio_simulation.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_portfolio_simulation.png")

# =============================================================================
# Chart 6: Top/Bottom Performers
# =============================================================================
print("Generating top/bottom performers chart...")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Top 5 alpha
top5 = bh_sorted.head(5)
ax1.barh(top5['Asset'], top5['Alpha'], color='#4ecdc4', edgecolor='white', linewidth=0.5)
ax1.set_xlabel('Alpha (%)')
ax1.set_title('Top 5 Alpha Generators', fontweight='bold')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)

for i, (asset, alpha) in enumerate(zip(top5['Asset'], top5['Alpha'])):
    ax1.text(alpha - 2, i, f'{alpha:+.1f}%', va='center', ha='right', fontweight='bold', color='white')

# Bottom 5 alpha
bottom5 = bh_sorted.tail(5)
ax2.barh(bottom5['Asset'], bottom5['Alpha'], color='#ff6b6b', edgecolor='white', linewidth=0.5)
ax2.set_xlabel('Alpha (%)')
ax2.set_title('Bottom 5 Underperformers', fontweight='bold')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)

for i, (asset, alpha) in enumerate(zip(bottom5['Asset'], bottom5['Alpha'])):
    ax2.text(alpha + 2, i, f'{alpha:+.1f}%', va='center', ha='left', fontweight='bold', color='white')

plt.tight_layout()
plt.savefig('reports/figures/bh_top_bottom.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
plt.close()
print("  ✓ Saved bh_top_bottom.png")

print("\n✅ All visualizations generated!")
print(f"   Output: reports/figures/")

# Print summary stats for report
print("\n" + "="*60)
print("SUMMARY STATISTICS FOR REPORT")
print("="*60)
print(f"Total assets tested: {len(bh_df)}")
print(f"Assets with trades: {(bh_df['Total_Trades'] > 0).sum()}")
print(f"Total trades: {bh_df['Total_Trades'].sum():.0f}")
print(f"Assets beating B&H: {(bh_df['Alpha'] >= 0).sum()}/{len(bh_df)} ({100*(bh_df['Alpha'] >= 0).mean():.0f}%)")
print(f"Average alpha: {bh_df['Alpha'].mean():+.2f}%")
print(f"Best alpha: {bh_df.loc[bh_df['Alpha'].idxmax(), 'Asset']} ({bh_df['Alpha'].max():+.2f}%)")
print(f"Worst alpha: {bh_df.loc[bh_df['Alpha'].idxmin(), 'Asset']} ({bh_df['Alpha'].min():+.2f}%)")
print(f"\nPortfolio simulation ($10K × {len(bh_df)} assets):")
print(f"  Starting: ${starting_capital:,.0f}")
print(f"  Strategy: ${total_strategy_value:,.0f} ({strategy_pct:+.1f}%)")
print(f"  Buy&Hold: ${total_buyhold_value:,.0f} ({buyhold_pct:+.1f}%)")
print(f"  Alpha: ${total_strategy_value - total_buyhold_value:,.0f}")
